"""scripts/train_scaffolded_s1.py — Stage 1: Imitation training.

Trains ScaffoldedPolicyNet to imitate the heuristic engine's move choices
and position evaluations using the dataset generated by gen_imitation_data.py.

Losses
------
  policy_loss : cross-entropy between softmax(logits) and one-hot(chosen_idx)
  value_loss  : MSE between value_head(value_input) and tanh(h_eval)

The policy loss teaches the network "prefer moves the heuristic prefers".
The value loss teaches the network "estimate how good the position is".

Since the heuristic already ranks moves correctly, this warmup gives the model
a solid starting policy — equivalent to the sentinel's own quality-scoring
ability but now expressed as a proper probability distribution over legal moves.

Usage
-----
    .venv/bin/python scripts/train_scaffolded_s1.py [options]

Options
-------
  --data    PATH    imitation_scaffolded.npz (gen_imitation_data.py output)
  --out-dir DIR     checkpoint directory (default learned_ai/checkpoints/scaffolded/s1)
  --epochs  N       number of training epochs (default 20)
  --batch   N       mini-batch size in positions (default 64)
  --lr      F       learning rate (default 1e-3)
  --dropout F       dropout probability (default 0.1)
  --val-frac F      fraction of data for validation (default 0.1)
"""

from __future__ import annotations

import argparse
import random
import sys
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F
from torch.optim import Adam
from torch.optim.lr_scheduler import CosineAnnealingLR

_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(_ROOT))

from learned_ai.models.scaffolded_net import ScaffoldedPolicyNet


def load_dataset(npz_path: str):
    """Load the .npz produced by gen_imitation_data.py.

    Returns (feat_matrices, value_inputs, chosen_idxs, h_evals, vn_evals).
    feat_matrices is a 1-D object array of variable-size (k_i, 62) arrays.
    vn_evals is all zeros when the dataset was generated without a value net.
    """
    data = np.load(npz_path, allow_pickle=True)
    feat_matrices = data["feat_matrices"]     # (N,) object array of (k, 62)
    value_inputs  = data["value_inputs"]      # (N, 23)
    chosen_idxs   = data["chosen_idxs"]       # (N,) int
    h_evals       = data["h_evals"]           # (N,) float
    # vn_evals present when dataset was generated with --value-net; zeros otherwise
    if "vn_evals" in data:
        vn_evals = data["vn_evals"]           # (N,) float
    else:
        vn_evals = np.zeros(len(h_evals), dtype=np.float32)
    return feat_matrices, value_inputs, chosen_idxs, h_evals, vn_evals


def train(args: argparse.Namespace) -> None:
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[s1] Device: {device}")

    # ── Load data ──────────────────────────────────────────────────────────────
    print(f"[s1] Loading {args.data} ...")
    feat_matrices, value_inputs, chosen_idxs, h_evals, vn_evals = load_dataset(args.data)
    N = len(chosen_idxs)
    has_vn = vn_evals.any()
    print(f"[s1] {N} positions loaded (value-net targets: {'yes' if has_vn else 'no'})")

    # Train/val split
    idxs = list(range(N))
    random.shuffle(idxs)
    n_val = max(1, int(N * args.val_frac))
    val_idxs   = idxs[:n_val]
    train_idxs = idxs[n_val:]
    print(f"[s1] Train: {len(train_idxs)}  Val: {len(val_idxs)}")

    # ── Model ─────────────────────────────────────────────────────────────────
    model = ScaffoldedPolicyNet(dropout=args.dropout).to(device)
    opt   = Adam(model.parameters(), lr=args.lr)
    sched = CosineAnnealingLR(opt, T_max=args.epochs, eta_min=args.lr * 0.01)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    best_val_loss = float("inf")

    # ── Training loop ──────────────────────────────────────────────────────────
    for epoch in range(1, args.epochs + 1):
        random.shuffle(train_idxs)
        model.train()

        ep_policy_loss = 0.0
        ep_value_loss  = 0.0
        n_batches      = 0

        for batch_start in range(0, len(train_idxs), args.batch):
            batch = train_idxs[batch_start : batch_start + args.batch]
            if not batch:
                continue

            policy_terms: list[torch.Tensor] = []
            vi_list:  list[np.ndarray] = []
            hev_list: list[float]      = []

            for i in batch:
                fm = feat_matrices[i]                      # (k, 62) numpy
                ci = int(chosen_idxs[i])
                feat = torch.tensor(fm, dtype=torch.float32).to(device)
                logits = model.policy_logits(feat)         # (k,)
                log_p  = F.log_softmax(logits, dim=-1)
                # Cross-entropy with one-hot target at chosen_idx
                policy_terms.append(-log_p[ci])
                vi_list.append(value_inputs[i])
                # Blend heuristic and value-net evals as value head target
                hev_list.append(0.5 * float(h_evals[i]) + 0.5 * float(vn_evals[i]))

            policy_loss = torch.stack(policy_terms).mean()

            # Value loss (batched)
            vi_t  = torch.tensor(np.stack(vi_list), dtype=torch.float32).to(device)
            val_pred = model.value(vi_t)                   # (B,)
            val_tgt  = torch.tensor(hev_list, dtype=torch.float32).to(device)
            value_loss = F.mse_loss(val_pred, val_tgt)

            loss = policy_loss + 0.5 * value_loss
            opt.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step()

            ep_policy_loss += float(policy_loss.item())
            ep_value_loss  += float(value_loss.item())
            n_batches      += 1

        sched.step()
        avg_pl = ep_policy_loss / max(n_batches, 1)
        avg_vl = ep_value_loss  / max(n_batches, 1)

        # ── Validation ─────────────────────────────────────────────────────────
        model.eval()
        val_pl = val_vl = 0.0
        n_val_b = 0
        with torch.no_grad():
            for batch_start in range(0, len(val_idxs), args.batch):
                batch = val_idxs[batch_start : batch_start + args.batch]
                if not batch:
                    continue
                p_terms: list[torch.Tensor] = []
                vi_list2: list[np.ndarray]  = []
                hev2:     list[float]       = []
                for i in batch:
                    fm = feat_matrices[i]
                    ci = int(chosen_idxs[i])
                    feat = torch.tensor(fm, dtype=torch.float32).to(device)
                    logits = model.policy_logits(feat)
                    log_p  = F.log_softmax(logits, dim=-1)
                    p_terms.append(-log_p[ci])
                    vi_list2.append(value_inputs[i])
                    hev2.append(0.5 * float(h_evals[i]) + 0.5 * float(vn_evals[i]))
                val_pl += float(torch.stack(p_terms).mean().item())
                vi_t2   = torch.tensor(np.stack(vi_list2), dtype=torch.float32).to(device)
                vp2     = model.value(vi_t2)
                vt2     = torch.tensor(hev2, dtype=torch.float32).to(device)
                val_vl += float(F.mse_loss(vp2, vt2).item())
                n_val_b += 1

        avg_val_pl = val_pl / max(n_val_b, 1)
        avg_val_vl = val_vl / max(n_val_b, 1)
        val_loss_total = avg_val_pl + 0.5 * avg_val_vl

        print(
            f"[s1] epoch {epoch:3d}/{args.epochs} | "
            f"train policy={avg_pl:.4f} value={avg_vl:.4f} | "
            f"val policy={avg_val_pl:.4f} value={avg_val_vl:.4f}"
        )

        ckpt = {
            "model":        model.state_dict(),
            "model_config": model.get_config(),
            "stage":        "s1",
            "epoch":        epoch,
            "val_loss":     val_loss_total,
        }
        torch.save(ckpt, out_dir / "latest.pt")

        if val_loss_total < best_val_loss:
            best_val_loss = val_loss_total
            torch.save(ckpt, out_dir / "best.pt")
            print(f"[s1]  → new best val_loss={val_loss_total:.4f}")

    print(f"\n[s1] Done. Best val_loss={best_val_loss:.4f}")
    print(f"[s1] Checkpoint: {out_dir / 'best.pt'}")


def main() -> None:
    p = argparse.ArgumentParser(description="Stage 1: imitation training")
    p.add_argument(
        "--data",
        default=str(_ROOT / "learned_ai" / "data" / "imitation_scaffolded.npz"),
    )
    p.add_argument(
        "--out-dir",
        default=str(_ROOT / "learned_ai" / "checkpoints" / "scaffolded" / "s1"),
    )
    p.add_argument("--epochs",   type=int,   default=20)
    p.add_argument("--batch",    type=int,   default=64)
    p.add_argument("--lr",       type=float, default=1e-3)
    p.add_argument("--dropout",  type=float, default=0.1)
    p.add_argument("--val-frac", type=float, default=0.1)
    args = p.parse_args()
    train(args)


if __name__ == "__main__":
    main()
